name: Build

on:
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install examples runtime dependencies
        run: sudo apt-get install -y libpcap-dev
      - name: Install linters
        run: rustup component add clippy rustfmt
      - name: Clippy
        run: cargo clippy -- -D warnings
      - name: Rustfmt
        run: cargo fmt --all -- --check
      - name: Run tests
        run: cargo test
      - name: Build
        run: cargo build --verbose --release
